### ISSUE TITLE
[Bug]: View [filament.widgets.world-clock-widget] not found.

### ISSUE THREAD

**Issue by edeoliv** [joaopaulolndev/filament-world-clock#3]
### What happened?

After installing the plugin and configuring it in adminpanel, the error "view not found" appears.

![imagen](https://github.com/joaopaulolndev/filament-world-clock/assets/76831154/3fec54d5-2cb3-4a35-8460-4eee709e9024)

### How to reproduce the bug

1. composer require joaopaulolndev/filament-world-clock
2. php artisan vendor:publish --tag="filament-world-clock-views"
3. php artisan vendor:publish --tag="filament-world-clock-translations"
4. In AdminPanel
```
FilamentWorldClockPlugin::make()
          ->timezones([
               'America/New_York',
               'America/Sao_Paulo',
               'Asia/Tokyo',
          ])
```
```

php artisan filament:clear-cached-components 
php artisan view:clear 
```

Does not correct the error

### Package Version

v1.0.0

### PHP Version

v8.3.8

### Laravel Version

v11.10.0

**Comment by joaopaulolndev** [comment]
Thanks for report @edeoliv 

Fixed on v1.0.1
