### ISSUE TITLE
African Flags not Loading

### ISSUE THREAD

**Issue by TonyOsadolor** [joaopaulolndev/filament-world-clock#4]
### What happened?

First of, Thanks for this amazing plugin, but currently African Flags don't get loaded, whenever you change timezone to any African Country, the flags breaks.

Though, I traced back to the function that calls the flags, (vendor\joaopaulolndev\filament-world-clock\src\Helpers\FlagsHelper.php)  and added Africa/Lagos to the list of array and pointed the assets to pick the Nigerian Flag from the list of flags

### How to reproduce the bug

->timezones([
   'Africa/Lagos',
 ])

### Package Version

1.0.4

### PHP Version

8.2.0

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by dharen008** [comment]
Same issue with Asia/Manila, is there a convenient way to add custom flag?

**Comment by TonyOsadolor** [comment]
> Same issue with Asia/Manila, is there a convenient way to add custom flag?

In my case, I just located the FlagHelper inside the package folder in vendors as so: vendor\joaopaulolndev\filament-world-clock\src\Helpers\FlagsHelper.php
and added Nigeria to the list of array, then point the flag picker to our country flag, you can check the short code for your country and replicate the format, but ending with your country short code

**Comment by joaopaulolndev** [comment]
Thank you @TonyOsadolor 

Please run the compose update to get the new version and after don't forget to publish the flags again as command below:

php artisan vendor:publish --tag=blade-flags --force

**Comment by joaopaulolndev** [comment]
> Same issue with Asia/Manila, is there a convenient way to add a custom flag?

@dharen008 
Oh, guy I finished the deployment right now.
Can you add this timezone inside the helper and open an MR?

src\Helpers\FlagsHelper.php

**Comment by joaopaulolndev** [comment]
Never mind @dharen008 , just update the package and you can use Asia/Manila

**Comment by dharen008** [comment]
I was about to do it, but you did it first. LOL, thank you @joaopaulolndev!

**Comment by joaopaulolndev** [comment]
Nice @dharen008 check my other plugin, I think you will like :)

**Comment by dharen008** [comment]
i will thank you again

**Comment by dharen008** [comment]
Hi @joaopaulolndev ,

I'm missing flags for America/Denver and Pacific/Guam again. Is there a way to make this dynamic? For example, gather all timezones with the same flags like America/STATE, Africa/STATE, Australia/STATE, etc., and separate those with different flags like ASIA/STATE, etc.

Also, please add a placeholder flag if no flag is assigned to a timezone.

I appreciate your hard work on this.

Thank you!
