### ISSUE TITLE
[Bug]: Some Suggested features

### ISSUE THREAD

**Issue by dharen008** [joaopaulolndev/filament-world-clock#5]
### What happened?

Add Date as well

Dynamic/Real-Time Time and Date
Currently, the clock does not update unless you refresh the page.

Add an option to show or hide the time and date.

### How to reproduce the bug

Dynamic Real-Time Clock and Date
Please add JavaScript code to ensure the time and date update automatically.
Also, include an option in the admin panel that allows users to choose whether to display or hide the date and time.

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by joaopaulolndev** [comment]
Hi @dharen008 

Already done in v1.0.7
Please run compose update 

Don't forge to publish the assets to work background

**Comment by dharen008** [comment]
Thank you @joaopaulolndev!
